const firebaseConfig={apiKey:"AIzaSyBkC75ZGm1iXXYdKR8lDNIP_l27RR5b8fM",authDomain:"mathswithmalindasirweb.firebaseapp.com",databaseURL:"https://mathswithmalindasirweb-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"mathswithmalindasirweb",storageBucket:"mathswithmalindasirweb.firebasestorage.app",messagingSenderId:"806771086827",appId:"1:806771086827:web:55978c72cac010a3d935ae"};
firebase.initializeApp(firebaseConfig);const db=firebase.database(),$=s=>document.querySelector(s);let users={},paymentId=null,showAll=false;
const now=new Date(),cycle=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`,free=now.getDate()<=14;
const studentEntries=()=>Object.entries(users).filter(([id])=>/^STU\d+$/i.test(id));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const grade=p=>({"grade6.html":"Grade 06","grade7.html":"Grade 07","grade8.html":"Grade 08","grade9.html":"Grade 09","grade10.html":"Grade 10","grade11.html":"Grade 11"}[p]||p||"—");
function effectiveStatus(x){if(x.status==="suspended")return"suspended";if(free)return"free";return x.paidFor===cycle&&x.paymentActive?"paid":"unpaid"}
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
function personRow(id,x,mode="student"){const st=effectiveStatus(x),isPay=mode==="payment";return `<div class="row"><div class="row-main"><b>${esc(x.fullName||"No name")} <small>${esc(id)} · ${grade(x.page)}${x.phone?` · ${esc(x.phone)}`:""}</small></b></div><span class="badge ${st}">${st==="free"?"Free period":st}</span><div class="row-actions">${isPay?`<button class="small-button ${st==="paid"?"":"warn"}" data-pay="${esc(id)}">${st==="paid"?"Update payment":"Verify & activate"}</button>`:`<button class="small-button" data-edit="${esc(id)}">Edit</button><button class="small-button" data-toggle="${esc(id)}">${x.status==="suspended"?"Restore":"Suspend"}</button><button class="small-button warn" data-delete="${esc(id)}">Remove</button>`}</div></div>`}
function render(){const list=studentEntries(),counts={total:list.length,active:0,paid:0,pending:0};list.forEach(([,x])=>{let s=effectiveStatus(x);if(s!=="suspended")counts.active++;if(s==="paid")counts.paid++;if(s==="unpaid"||s==="suspended")counts.pending++});$("#totalCount").textContent=counts.total;$("#activeCount").textContent=counts.active;$("#paidCount").textContent=counts.paid;$("#pendingCount").textContent=counts.pending;
const attention=list.filter(([,x])=>["unpaid","suspended"].includes(effectiveStatus(x))).slice(0,8);$("#attentionList").innerHTML=attention.length?attention.map(([id,x])=>personRow(id,x,"payment")).join(""):`<div class="row"><div class="row-main"><b>All clear</b><small>No students need payment attention right now.</small></div></div>`;
const q=$("#studentSearch").value.toLowerCase(),gf=$("#gradeFilter").value;const filtered=list.filter(([id,x])=>(!gf||x.page===gf)&&(`${id} ${x.fullName||""} ${x.phone||""}`).toLowerCase().includes(q));$("#studentsList").innerHTML=filtered.length?filtered.map(([id,x])=>personRow(id,x)).join(""):`<div class="row"><div class="row-main"><b>No students found</b></div></div>`;
const pays=list.filter(([,x])=>showAll||effectiveStatus(x)!=="paid");$("#paymentsList").innerHTML=pays.length?pays.map(([id,x])=>personRow(id,x,"payment")).join(""):`<div class="row"><div class="row-main"><b>No payments awaiting review</b></div></div>`;
}
function openStudent(id){const x=users[id]||{};$("#formTitle").textContent=id?"Edit student":"Add student";$("#editId").value=id||"";$("#studentId").value=id||"";$("#studentId").disabled=!!id;$("#studentPasscode").value=x.passcode||"";$("#studentFullName").value=x.fullName||"";$("#studentPhone").value=x.phone||"";$("#studentPage").value=x.page||"grade6.html";$("#studentStatus").value=x.status||"active";$("#studentDialog").showModal()}
$("#adminLogin").addEventListener("submit",async e=>{e.preventDefault();const msg=$("#lockMessage");msg.textContent="Checking access…";try{const snap=await db.ref("users/admin").get();if(snap.exists()&&snap.val().passcode===$("#adminPasscode").value){sessionStorage.setItem("mwmAdmin","1");unlock()}else msg.textContent="Incorrect admin passcode."}catch(err){console.error(err);msg.textContent="Firebase could not read users/admin. Check your Realtime Database Rules and make sure admin.js is uploaded beside this file."}});
function unlock(){$("#adminLock").hidden=true;$("#app").hidden=false;$("#monthLabel").textContent=`PAYMENT CYCLE · ${now.toLocaleString("en-US",{month:"long",year:"numeric"})} · ${free?"FREE PERIOD":"PAYMENT REQUIRED"}`;db.ref("users").on("value",s=>{users=s.val()||{};render()})}
if(sessionStorage.getItem("mwmAdmin"))unlock();$("#signOut").onclick=()=>{sessionStorage.removeItem("mwmAdmin");location.reload()};
document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.view||b.dataset.open){let v=b.dataset.view||b.dataset.open;document.querySelectorAll(".view").forEach(x=>x.hidden=x.id!==v);document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#viewTitle").textContent=v[0].toUpperCase()+v.slice(1)}if(b.id==="addStudent")openStudent();if(b.dataset.edit)openStudent(b.dataset.edit);if(b.dataset.toggle){let x=users[b.dataset.toggle];await db.ref(`users/${b.dataset.toggle}`).update({status:x.status==="suspended"?"active":"suspended"});toast("Student status updated.")}if(b.dataset.delete&&confirm(`Remove ${b.dataset.delete}? This cannot be undone.`)){await db.ref(`users/${b.dataset.delete}`).remove();toast("Student removed.")}if(b.dataset.pay){paymentId=b.dataset.pay;let x=users[paymentId];$("#paymentStudent").textContent=`${x.fullName||paymentId} · ${paymentId}`;$("#paymentNote").value=x.paymentNote||"";$("#paymentDialog").showModal()}if(b.dataset.close) b.closest("dialog").close();if(b.id==="showAllPayments"){showAll=!showAll;b.textContent=showAll?"Show pending":"Show all";render()}if(b.id==="resetPayments"&&confirm("Mark every student unpaid for this month?")){let updates={};studentEntries().forEach(([id])=>updates[`users/${id}/paymentActive`]=false);await db.ref().update(updates);toast("All student payments reset.")}});
$("#studentSearch").oninput=render;$("#gradeFilter").onchange=render;
$("#studentForm").addEventListener("submit",async e=>{e.preventDefault();const old=$("#editId").value,id=old||$("#studentId").value.trim().toUpperCase();if(!/^STU\d+$/i.test(id))return toast("Use a student ID such as STU1001.");if(!old&&(await db.ref(`users/${id}`).get()).exists())return toast("That Student ID already exists.");let prior=users[id]||{};await db.ref(`users/${id}`).set({...prior,passcode:$("#studentPasscode").value.trim(),fullName:$("#studentFullName").value.trim(),phone:$("#studentPhone").value.trim(),page:$("#studentPage").value,status:$("#studentStatus").value,paymentActive:prior.paymentActive||false,paidFor:prior.paidFor||""});$("#studentDialog").close();toast("Student saved.")});
$("#paymentForm").addEventListener("submit",async e=>{e.preventDefault();await db.ref(`users/${paymentId}`).update({paymentActive:true,paidFor:cycle,paymentNote:$("#paymentNote").value.trim(),paymentVerifiedAt:new Date().toISOString()});$("#paymentDialog").close();toast("Payment activated for this month.")});
